---
- name: Creating vault folder.
  file:
    dest: '{{ vault_path }}/{{ item.path }}'
    state: 'directory'
    owner: '{{ item.owner }}'
    group: '{{ item.owner }}'
    mode: '{{ item.mode }}'
  loop:
    - { path: 'backup', owner: 'root', mode: '0755' }
    - { path: 'backup/vault', owner: '{{ vault_arg.user }}', mode: '0750' }

- name: Creating Rclone configureation folder.
  file:
    dest: '/etc/rclone'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when:
    - vault_backupset_arg.cloud_rsync | bool
    - vault_backupset_arg.cloud_drive is defined

- name: Rclone configuration file transfer.
  template:
    src: 'rclone.conf.j2'
    dest: '/etc/rclone/vault.conf'
    owner: '{{ vault_arg.user }}'
    group: '{{ vault_arg.user }}'
    mode: '640'
  when:
    - vault_backupset_arg.cloud_rsync | bool
    - vault_backupset_arg.cloud_drive is defined

- name: Vault backup scripts file transfer.
  template:
    src: 'vault_backup.sh.j2'
    dest: '/usr/local/bin/vault_backup.sh'
    owner: '{{ vault_arg.user }}'
    group: '{{ vault_arg.user }}'
    mode: '640'

- name : Vault backup job.
  cron:
    user: '{{ vault_arg.user }}'
    name: 'Vault Snapshot backup'
    minute: "{{ 60 | random(seed=inventory_hostname) }}"
    hour: "{{ 6 | random(seed=inventory_hostname,step=1) }}"
    job: '/bin/sh /usr/local/bin/vault_backup.sh'
  no_log: true
